global using Repository.Base;
global using Selector.Core.Domain.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Selector.Infrastructure.Persistence.Context;
global using Selector.Infrastructure.Persistence.Repository;
global using Selector.Infrastructure.Persistence.EntityTypeConfigurations;
global using Selector.Core.Application.Interfaces;
global using System.Linq.Expressions;